apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::715841341777:user/rohith_rk66
      username: admin
      groups:
        - system:masters
