apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: devops-assignment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
        prometheus.io/path: "/metrics"
      containers:
        - name: frontend
          image: docrohith/frontend-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
        
          envFrom:
            - configMapRef:
                name: frontend-config